### ISSUE TITLE
/usr/bin/echo: not found

### ISSUE THREAD

**Issue by marcin42** [fogger/echo#1]
When I run the image, I get the following error message.
```
$ docker run -it --rm fogger/echo:0.6.2
/bin/sh: /usr/bin/echo: not found
```

When I build the image locally (and skip running fogger-builder), it starts up without any problems.
```
$ ./builder/build.sh
$ docker build -t fogger/echo:exp ./builder/docker/amd64
$ docker run -it --rm fogger/echo:exp
2016/07/20 12:49:02 Start endpoint localhost:6000
```

**Comment by randomsid** [comment]
fixed by adding CGO_ENABLED=0 to build command (build.sh)
